### PR TITLE
Update APIReference-TypeSystem.md

### PR DESCRIPTION
**Pull request by Artsem-Mardvinau**
just a comma missed out

### CODE REVIEW

**Comment by carolstran** [comment]
Hey hey 👋🏼  the Gatsby migration (#938) has been merged so now we can update the content again. Could you please resolve the conflicts on your branch?

**Review by hwillson — APPROVED** [review]
Ooops - that comma is definitely important, thanks @Artsem-Mardvinau!

**Comment by hwillson** [comment]
@Artsem-Mardvinau sorry for the delay here but if you can sign the new CLA (instructions above) we'll get this merged. Thanks!

**Comment by dimaMachina** [comment]
@Urigo this can be closed, I fixed it too when did Nextra migration

**Pull request closed without merging**
