### PR TITLE
Add Ballerina language and ballerina-graphql to language support

### PR DESCRIPTION
**Pull request by ThisaruGuruge**
## Description

Ballerina is a new programming language mainly focusing on integration and the cloud. Ballerina comes with a rich set of standard libraries, of which `GraphQL` is also a part. Ballerina GraphQL is now spec-compliant and we would like to list it under the GraphQL language support section. This PR adds the `ballerina-graphql` under the `ballerina` language, where the client and server is added.

### CODE REVIEW

**Comment by ThisaruGuruge** [comment]
@hwillson this is my first contribution. Can you please let me know if there is anything more to be done here?

**Comment by ThisaruGuruge** [comment]
Sorry for the noise, but mentioning some of the maintainers for attention.
@leebyron @hwillson @benjie @michaelstaib Can you please let me know if there's any issue with this PR?

**Review by hwillson — APPROVED** [review]
Thanks @ThisaruGuruge - looks great!

**Comment by ThisaruGuruge** [comment]
Thank you, @hwillson

**Pull request merged**
