### PR TITLE
fix: learn pages crashing due to codemirror

### LINKED ISSUE #1400: learn pages become blank after a moment
### Description

When I open https://graphql.org/learn/introspection/ page, it shows the page at the beginning, but it becomes blank after a moment.

### Steps to Reproduce

open the https://graphql.org/learn/introspection/ page

### Expected Result 

The page doesn't become blank

### Actual Result 

it shows white page

### Additional Context

My browser is Chrome Version 111.0.5563.146 (Official Build) (arm64) on MacOS
I also checked it with my Android Chrome browser and it shows the same result.

### PR DESCRIPTION
**Pull request by dannyhw**
Closes #1400

## Description

I noticed that some things broke on /learn due to codemirror changes

After looking into it a bit code mirror 6 has breaking changes and updating it without adjusting implementation causes the learn pages to crash

I reverted some changes from https://github.com/graphql/graphql.github.io/commit/3db0010ffdd2fceb28ea1450bf9621bb97da33d9 and it seems to work again

test by visiting the learn queries/mutations page

heres the codemirror migration guide
https://codemirror.net/docs/migration/

### CODE REVIEW

**Comment by dannyhw** [comment]
sorry to ping you @TuvalSimha but maybe you can check since I'm reverting some of your changes here

**Comment by Urigo** [comment]
thank you so much @dannyhw!

@TuvalSimha let's open another PR with a fix including the latest version

**Comment by dannyhw** [comment]
@Urigo happy to help, this website has been really helpful for me :). Thanks for merging so quick, now I can get back to learning 🤓

**Comment by TuvalSimha** [comment]
@dannyhw thank you!

**Pull request merged**
