### PR TITLE
Add Escape.tech – GraphQL Security, GraphQL.Security & GraphQL Armor

### PR DESCRIPTION
**Pull request by iCarossio**
Add Escape.tech – GraphQL Security, GraphQL.Security & GraphQL Armor :)

### CODE REVIEW

**Comment by hwillson** [comment]
👋 @iCarossio - thanks for this; if you can sign the CLA we'll get this merged.

**Comment by iCarossio** [comment]
Hello @hwillson, I signed the NDA months ago but I did not figure out how to make your system work…
0F1466D6-76D1-422A-89EA-606ECCB04C4C

**Comment by hwillson** [comment]
Thanks @iCarossio - very bizarre. You've definitely signed, so I'll override/merge.

**Review by hwillson — APPROVED** [review]
Thanks @iCarossio!

**Comment by iCarossio** [comment]
Yes this is super strange! Thank you @hwillson !

**Pull request merged**
