### PR TITLE
Conf page

### PR DESCRIPTION
**Pull request by TuvalSimha**
Hey @leebyron, how are you?

So Uri talks with me about the `/conf` page. For this moment this is a draft pull request, you can run it and explore the new path `/conf`. This is not the final result of course, but I will be happy to get your feedback. I will continue with this work tomorrow.

Missing:
1. Header
2. Footer herf links
3. CTA herf links

### CODE REVIEW

**Comment by TuvalSimha** [comment]
https://user-images.githubusercontent.com/37614975/229169903-eed90872-8875-4ad8-9f0d-33ffe218e33c.mp4

@Urigo  @leebyron

**Comment by leebyron** [comment]
Super excited to review this! Thank you for jumping on the task so quickly.

I'm on my way into an airplane now so will review this a bit late, but in the meantime I've shared a bunch of prep docs with @Urigo so he should be equipped to help review until then

**Comment by leebyron** [comment]
The video is really promising. Great work so far

**Review by leebyron — COMMENTED** [review]
I noticed when rendering the main page of graphql.org that the introduction of tailwind caused some h2 and img elements to display incorrectly.

Would you mind comparing old and new to ensure tailwind didn't break too many things?

**Comment by leebyron** [comment]
I hope you don't mind I took the liberty of adding a batch of changes in the commit above.

Still plenty of progress to be done, thanks for getting this going!

**Comment by leebyron** [comment]
I'm not very familiar with tailwind, but I think the rendering issue is that tailwind's reset CSS is getting added to the page *after* the full set of compiled less files, and _css/graphql.less has some resets of its own.

~I don't know how to resolve this~
Fix incoming!

**Comment by leebyron** [comment]
I was able to make a bit more progress and am signing off for a while. I'll check back in about 12hr to see if I can help from there.

**Comment by dotansimha** [comment]
@leebyron we are pushing design changes and also making it responsive. Trying to keep up with your changes and make sure we are not conflicting :) 
Next: Speakers section (also needs to bring it back to the first fold), Pricing section and some general structure improvements

**Comment by leebyron** [comment]
Whoops, sorry for the toe-stepping. I just got the expanded SEO & Social in place - I'll hold on touching anything else there while you all jam. Awesome!

**Comment by leebyron** [comment]
I've gotten all FAQ content in place.

I noticed at some point with the revamped design that those pages lost styles. I think it's just a matter of styling header, ul, and a tags appropriately.

I'm sure you're aware mobile views still has some layout issues as well

I'll check back in morning my time to handle any loose ends, but if you think you have everything polished up and tested then you have my blessing to merge this

**Comment by Urigo** [comment]
@leebyron should we change "Register Now!" to something like "Buy Tickets" or something more simple?

**Review by dotansimha — APPROVED** [review]

**Comment by leebyron** [comment]
Ah looking good!

On mobile I'm still seeing some layout issues with content wider than the screen width

**Comment by Urigo** [comment]
@leebyron can you share a screenshot?
Also, make sure to check out the latest, we've merged a couple of more PRs since
https://graphql.org/conf/

**Pull request merged**
