### PR TITLE
iGTB-logo

### PR DESCRIPTION
**Pull request by rhuiser**
Added iGTB as graphQL user.

### CODE REVIEW

**Comment by leebyron** [comment]
Closing aging PR - feel free to reopen if you have changes

**Comment by rhuiser** [comment]
How do I re-open this PR?

**Comment by wincent** [comment]
I re-opened it for you @rhuiser. (An other alternative is to just push to a new branch and create a new PR.)

**Comment by rhuiser** [comment]
Thanks!!!! 
I missed the initial request for cropping the image.

Will do now

Robin

**Comment by wincent** [comment]
This is getting stale again, so going to close it. If you'd like to address the feedback here @rhuiser and resubmit it as a new PR we'll be happy to merge it. Thanks once again!

**Comment by rhuiser** [comment]
I understand. Indeed have this tab open for weeks in my browser, not able to find time to update. Will open another PR later on.

Thanks for re-opening and sorry for not updating.

**Pull request closed without merging**
