### PR TITLE
Add GraphQL Wroclaw to a meetup list

### PR DESCRIPTION
**Pull request by milosjaros**
Hi there, I've added GraphQL Wroclaw (500+ members) to a list of Europe meetups. Thanks!

### CODE REVIEW

**Comment by milosjaros** [comment]
Thank you. The corporate CLA is signed now.

**Comment by milosjaros** [comment]
Is there anything more I can do?

**Comment by carolstran** [comment]
👋🏼 Thanks for taking the time to open this pull request! We're currently re-evaluating the structure of this Community page and pausing any changes until after those decisions are made. So I'm going to mark this PR as `On hold` and if you have any thoughts on this topic, it'd be great if you could voice them in #912

**Comment by carolstran** [comment]
Hey hey 👋🏼  the Gatsby migration (#938) has been merged so now we can update the content again. Could you please resolve the conflicts on your branch?

**Comment by hwillson** [comment]
👋 @milosjaros - sorry for the long delay here; the GraphQL Wroclaw meetup looks awesome! If you don't mind signing the new CLA (instructions above) we can get this merged. Thanks!

**Comment by Urigo** [comment]
thank you!
Added [here](https://github.com/graphql/graphql.github.io/pull/1403)

**Pull request closed without merging**
