### PR TITLE
Added smooth scrolling behavior

### LINKED ISSUE #1314: Add smooth scrolling when clicking on section links
### Description

This is a very minor improvement that  could be made to the website, I noticed that when you click on a particular section, it automatically just takes you to that section. Works as intended, but You can easily get lost where you are, since it magically teleports you there. Adding smooth scrolling would help with this issue, and let the reader know where the page is taking them. 

### Motivation
Mild UI improvements for the user. 

### Collaboration
I can build this out.  Or if someone wants to do it

### Additional Context
Example of the thing I'm talking about. It just snaps to that section, adding smooth scrolling would scroll the page to that section, so the reader doesn't get lost. 
Animation

### PR DESCRIPTION
**Pull request by Lokprakash-babu**
Closes #1314 

## Description

Adds smooth scrolling for better UX.

### CODE REVIEW

**Comment by Urigo** [comment]
@TuvalSimha what do you think about it?

**Comment by TuvalSimha** [comment]
@Urigo Let's merge it, can help a lot to pages with a lot of content to read.

@Lokprakash-babu Thank you!

**Comment by TuvalSimha** [comment]
@Urigo 
Let's wait with that, I will work on some UI fixes (also with back to top button for pages with very scrolling)

**Comment by dimaMachina** [comment]
@Urigo this can be closed

**Pull request closed without merging**
