### PR TITLE
Add Ariadne to Python libraries list

### PR DESCRIPTION
**Pull request by rafalp**
**[Ariadne](https://github.com/mirumee/ariadne/)**

Ariadne is Python library for implementing GraphQL servers:

- It's schema first
- Written for Python 3.7+
- Batteries included: Async, ASGI, WSGI, Django, Flask, Starlette
- [It has extensive documentation rich in examples and guides](https://ariadnegraphql.org/)

### CODE REVIEW

**Comment by MrOrz** [comment]
I was just about to submit similar PR on the same topic. I hope this can be merged soon. Python community deserves a well-documented, schema-first GraphQL implementation!

**Comment by carolstran** [comment]
👋🏼 Thanks for taking the time to open this pull request! We're currently re-evaluating how we handle contributions to this Code page and pausing any changes until after those decisions are made. So I'm going to mark this PR as `On hold` and if you have any thoughts on this topic, it'd be great if you could voice them in #911

**Comment by carolstran** [comment]
Hey hey 👋🏼  the Gatsby migration (#938) has been merged so now we can update the content again. Could you please resolve the conflicts on your branch?

**Comment by rafalp** [comment]
@carolstran thanks for heads up! I'll open new PR with this!

**Comment by rafalp** [comment]
Here's new PR: https://github.com/graphql/graphql.github.io/pull/950

**Pull request closed without merging**
