### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ardatan**

### CODE REVIEW

**Review by saihaj — CHANGES_REQUESTED** [review]
We can use the [new JSX transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#gatsby). React team provides a codemod to remove all `import React from ‘react’`

**Comment by orta** [comment]
Do you want to do the transformed @ardatan? I don't end either way

**Comment by ardatan** [comment]
I was afraid of breaking things. Let's leave it in a different PR.

**Comment by saihaj** [comment]
We could have used this new transform syntax in #938 since that was a feature added in v16.14 but I missed to point that out in review. 

According to [release blog post](https://reactjs.org/blog/2020/10/20/react-v17.html#react). They changed event delegation and a few other non breaking issues. I don’t think any of the changes will affect us. Purpose of this version is to make it easier to gradually upgrade react’s future versions.

Sure we can get that in a new PR

**Comment by Urigo** [comment]
I've reviewed and everything works as expected so I'm merging, but that doesn't mean we shouldn't move to the new JSX transform as @saihaj suggested!
I suggest we'll try from now on to keep PRs small and easy to merge, so we could move more quickly.

@saihaj that's a good idea, are you up to creating a new PR with the new transform?

**Comment by saihaj** [comment]
I can get something in today

**Comment by saihaj** [comment]
@Urigo turns out gatsby has disabled automatic JSX runtime temporarily https://github.com/gatsbyjs/gatsby/pull/27615. We need to wait for a new Gatsby release before we refactor.

**Pull request merged**
