### PR TITLE
write a bunch of homepagey things

### PR DESCRIPTION
**Pull request by lacker**
I took a stab at updating a bunch of homepage content based on your "straw man" outline. No "visual metaphors" or anything but I think the content is decent. I'm not all the way through but if this looks good I'll pick up from here. Feedback plz! @leebyron 

What the home page looks like after this:

x

### CODE REVIEW

**Comment by leebyron** [comment]
Sweet thanks. Here's what I've got so far for the home page sections:


**Describe your app's data**

```
type Project {
  name: String
  tagline: String
  contributors: [User]
}
```

**Ask for what you need**
```
{
  project(name: "GraphQL") {
    tagline
  }
}
```

**Get predictable results**
```
{
  "project": {
    "tagline": "A query language for your API"
  }
}
```


**A query language for your API**

GraphQL is a query language for APIs and a runtime for fulfilling those queries with your existing data. GraphQL provides a complete and understandable description of the data in your API, gives clients the power to ask for exactly what they need and nothing more, makes it easier to evolve APIs over time, and enables powerful developer tools. GraphQL was built at Facebook and has powered its mobile applications since 2012.

**Ask for what you need, get exactly that.**

[Illustration: just a simple query and response?]

Send a GraphQL query to your API and get exactly what you need, nothing more and nothing less. GraphQL queries always return predictable results. Apps using GraphQL are fast and stable because they control the data they get, not the server.

**Access many resources in a single request.**

[Illustration: a query 2 or 3 levels deep]

GraphQL queries access not just the properties of one resource but also smoothly follow references between them. While typical APIs require loading from multiple URLs, GraphQL APIs get all the data your app needs in a single request. Apps using GraphQL are quick even on slow mobile network connections.

**Describe what's possible with a type system.**

[Illustration of a type IDL following a query by line]

[Under: a server <-> client (Capabilities, Requirements)]?

GraphQL presents an API organized in terms of objects, types, and fields, not endpoints. GraphQL APIs provide a complete description of your data, exposing the full set of capabilities available from a single endpoint. APIs use these types to ensure Apps only ask for what's possible and provide clear and helpful errors. Apps can use these types to avoid writing manual parsing and model code.

**Move faster with powerful developer tools.**

[Illustration of GraphiQL validation error and typeahead, animated?]

Know exactly what data you can request from your API without leaving your editor, highlight potential issues before sending a query, and take advantage of improved code intelligence. GraphQL introspection makes it easy to build new powerful tools by leveraging a GraphQL API's type system. You can even automatically generate your API documentation.

**Evolve your API without versions.**

[Illustration showing more legs added to a graph? Or a type evolving over time?]

Add new fields and types to a GraphQL API without affecting queries sent from existing apps. Aging fields can be deprecated and hidden from documentation. By using a single version, GraphQL APIs give apps easier access to new features and enable cleaner, more maintainable server code.

**Powered by your existing data and code.**

[Illustration of each field becoming a function?]

GraphQL creates a uniform, powerful API across the entire surface area of your application without being limited by a specific storage engine. Write GraphQL APIs that leverage your existing data model and server with GraphQL engine implementations available in many languages. You provide small functions that fulfill fields in the type system, and GraphQL calls them with optimal concurrency.



[ Learn More ]   [ Get Started ]

**Comment by lacker** [comment]
Ehhh, ok our content is like half overlapping here. I probably should have not jumped in on the homepage, I was just guessing you hadn't written much for it yet.

OK so to make progress how about this. There are basically 6 components to the content in this pull request:

1. The tagline "A query language for APIs"
2. The "powerful" block above the fold
3. The "efficient" block above the fold
4. The "strongly typed" block above the fold
5. The query-response section
6. The "schema language" section

Which of those do you like in this PR and which don't you really like? If you give me some feedback on that then I can try to smush this PR together with your content & update this PR.

**Comment by leebyron** [comment]
I'm all about that tagline. Pretty great that it's almost exactly the same as what I arrived at!

I'm working out visual aids for the bold points above but I'm open to improvements for the copy within each section.

I'm dropping the three-bullet block format on the homepage in favor of the new structure, so I don't know that your 2-4 will be preserved as written, we should make sure the same points are being made in the new format.

I think the longer-form prose you're writing here is good, but probably better suited for the introduction chapter in Learn, what do you think?

**Comment by lacker** [comment]
Well yeah I just copied the tagline from the first sentence I could find in your "strawman" PR that started with "GraphQL is" ;-)

OK, so I'll move the longer-form prose to separate pages and use that to start an intro chapter. I'll do that in a separate PR. In terms of continuing this PR, I think I should probably wait til you have the structure you want to replace the three-bullet-point, and then try to smush things in there.

**Comment by leebyron** [comment]
:+1:

**Comment by lacker** [comment]
I'm just gonna close this & go work on the "code" section - maybe I'll smush this content somewhere else later but I'll wait until at least the first drafts of the "code" and "learn" parts are done.

**Pull request closed without merging**
