### PR TITLE
Add DEV Community's GraphQL tag to community page

### PR DESCRIPTION
**Pull request by belhassen07**
[DEV Community](https://dev.to) is a burgeoning source of guidance and discussion on software topics, especially web dev. This will be a useful link to point to the official place to discuss GraphQL matters on the platform.

A few additional links pertaining to dev.to

Traffic stats: https://www.similarweb.com/website/dev.to
Twitter: https://twitter.com/thepracticaldev
GraphQL tag (as included in PR): https://dev.to/t/graphql

Some example GraphQL posts:
https://dev.to/xngwng/rest-vs-graphql-apis-the-good-the-bad-the-ugly-34i8
https://dev.to/grigorkh/what-is-graphql-4n9j
https://dev.to/aurelkurtula/creating-a-movie-website-with-graphql-and-react-25d4
Happy coding :heart:

### CODE REVIEW

**Comment by belhassen07** [comment]
I've signed up after the bot comment, I hope someone can review and merge this PR, Thanks!

**Comment by stubailo** [comment]
While I do like DEV a lot, I think it would fit better in the "blogs" section. Right now this PR positions it as one of the main resources, which I think is somewhat premature at the moment.

**Comment by orta** [comment]
Yep, agreed, if you move this down to the blogs section - I'll merge it 👍

**Comment by carolstran** [comment]
Hey @belhassen07, I know this PR is from years ago - but are you still planning to update it? Otherwise, I can open a new PR for this since it was already approved 😊

**Comment by carolstran** [comment]
Nevermind my earlier comment. Instead, we're re-evaluating the structure of this Community page and pausing any changes until after those decisions are made. So I'm going to mark this PR as `On hold` and if you have any thoughts on this topic, it'd be great if you could voice them in #912

**Comment by carolstran** [comment]
Hey hey 👋🏼  the Gatsby migration (#938) has been merged so now we can update the content again. Could you please resolve the conflicts on your branch?

**Comment by hwillson** [comment]
@belhassen07 I know this is an old one (sorry!) but if there's any chance you're still around and would be able to sign the new CLA, we'll get this merged.

Note to all - as discussed in this PR thread I've moved the changes down to the Blogs section and adjusted the content a bit for brevity.

**Comment by Urigo** [comment]
also agree with @orta that this would fit in the blogs section.
Especially after this change because its not an individual post but a blog to follow: https://github.com/graphql/graphql.github.io/pull/1288

**Comment by Urigo** [comment]
done [here](https://github.com/graphql/graphql.github.io/pull/1316)

**Pull request closed without merging**
