### PR TITLE
A link to the graphql implementation in D

### PR DESCRIPTION
**Pull request by burner**
At a link to the graphql server implementation for the D Progamming Language (dlang.org)

### CODE REVIEW

**Comment by burner** [comment]
any progress on this?

**Comment by carolstran** [comment]
👋🏼 Thanks for taking the time to open this pull request! We're currently re-evaluating how we handle contributions to this Code page and pausing any changes until after those decisions are made. So I'm going to mark this PR as `On hold` and if you have any thoughts on this topic, it'd be great if you could voice them in #911

**Comment by carolstran** [comment]
Hey hey 👋🏼  the Gatsby migration (#938) has been merged so now we can update the content again. Could you please resolve the conflicts on your branch?

**Comment by burner** [comment]
@carolstran thank you for the info. I just rebased. Let me know if there is something else to do.

**Review by carolstran — APPROVED** [review]
Looks great @burner, thank you for taking the time to contribute (and rebase). Merging now 🚀

**Comment by burner** [comment]
@carolstran thank you

**Pull request merged**
