### PR TITLE
Restore /swapi-graphql endpoint via reverse proxy

### LINKED ISSUE #1427: Getting 404 on /swapi-graphql
### Description

I'm getting a 404 on the https://graphql.org/swapi-graphql route. I have definitely gone to this route in the past but it is no longer working. The reverse proxying doesn't seem to be working.

https://github.com/graphql/graphql.github.io/blob/7d5374d5fc9c8085652efa240c92ede4f2423641/static/_redirects#L4-L5

### PR DESCRIPTION
**Pull request by acao**
Closes #1427

## Description

restore 200 reverse proxy rewrite logic for swapi-graphql

### CODE REVIEW

**Review by benjie — APPROVED** [review]
LGTM.

Note to self: though this says `createRedirect` what's actually happening is that Gatsby is creating a reverse proxy (hence the `statusCode: 200`) - odd choice of name for that API but 🤷

**Comment by benjie** [comment]
Should also fix https://github.com/graphql/swapi-graphql/issues/219

**Comment by acao** [comment]
@Urigo if you get a chance!

**Comment by benjie** [comment]
It worked on the preview so I've merged it 🤷

**Pull request merged**
