### PR TITLE
Update Community-Events.md

### PR DESCRIPTION
**Pull request by gsans**
Added few talks.

### CODE REVIEW

**Comment by stubailo** [comment]
I'm not sure about this one - should we have talks that have already happened on the site? Curious what @theadactyl thinks about this one.

**Comment by gsans** [comment]
I think that's how it's being use right now as you don't remove old events. The first event of the current list is from 15th September. 

I also think the ordering should be reversed if you don't remove old events.

**Comment by theadactyl** [comment]
I think we should be removing old events for sure. Will take another look
at this PR and how we should be maintaining event listings later today.

**Comment by leebyron** [comment]
I agree with @stubailo - let's keep this page reserved for future events! Not a lot to gain by linking to events that have already occurred.

If there are high quality videos introducing new content, then we could add those to the community section on videos?

**Pull request closed without merging**
