### PR TITLE
Update README and remove unnecessary assets

### PR DESCRIPTION
**Pull request by lucperkins**

### CODE REVIEW

**Comment by carolstran** [comment]
👋🏼 @lucperkins, I definitely agree that the README could use an update and I like those changes, but I'm curious about the decision for the other pages? It'd be great to have more context.

**Comment by lucperkins** [comment]
@carolstran Beyond the README, the PR is simply removing assets that are no longer necessary

**Comment by IvanGoncharov** [comment]
@lucperkins Reverting my changes, it looks like you are right and we moved to Netlify at some point.
However, before merging it I like to ensure it in sync with our Netlify setup, e.g. we use `npm install` and not `yarn`.

**Comment by carolstran** [comment]
@lucperkins Would you be open to having this PR only be the README changes and opening the rest as a separate PR? I'd love to get the README changes merged in time for Hacktoberfest 🎃

**Pull request closed without merging**
