### PR TITLE
Fix Loggi logo on GraphQL users

### PR DESCRIPTION
**Pull request by kreigne**
The previous logo had lost some pixels during resize, this is fixed.

### CODE REVIEW

**Comment by kreigne** [comment]
@leebyron Sorry for that, our design team just checked our logo and said it was missing some pixels, now it's fixed.

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by leebyron** [comment]
Ah - perhaps a little aggressive on the margin crop. This looks nice, thanks

**Comment by kreigne** [comment]
Thank you!

**Pull request merged**
