### PR TITLE
Add entries for cppgraphqlgen to the C/C++ section

### PR DESCRIPTION
**Pull request by wravery**
## Description

Both of these libraries/tools are part of the [microsoft/cppgraphqlgen](https://github.com/microsoft/cppgraphqlgen) project, but I split them into separate entries to make it clear that it supports generating both client and server implementations in C++.

The markdown looks fine to me in a previewer, but I haven't been able to get the site to run the "Code" page locally (with or without my addition) to verify these changes look OK on the site.  It throws an error trying to dereference an undefined `data` variable on my machine. If there are any problems with the formatting or the way this looks on a working build, please feel free to send it back for fixes.

Thanks!

### CODE REVIEW

**Comment by benjie** [comment]
@wravery I believe Microsoft already have a CLA in place with GraphQL Foundation, so you need to reach out to whatever internal team manages that and have your username added to it. Once done, click the link in the EasyCLA comment above to have it re-evaluate.

**Comment by wravery** [comment]
@benjie Thanks! I am waiting to hear back from the team that I think would manage this CLA, I'll trigger the reevaluation once I do.

**Comment by wravery** [comment]
@benjie just bumping this for awareness since I've signed the CLA and reevaluated the check.

After consulting with the team that EasyCLA knew about and their legal contact, they recommended that I just sign it as a personal CLA. There is no central oversight for this particular CLA at Microsoft, nor did they want to take on that responsibility.

**Review by saihaj — APPROVED** [review]
thank you and sorry for the delays

**Pull request merged**
