### PR TITLE
Fix typo GraphiQL -> GraphQL

### PR DESCRIPTION
**Pull request by jen729w**
Typo fix.

### CODE REVIEW

**Comment by jen729w** [comment]
CLA ticked. ☑️

**Comment by stubailo** [comment]
This is actually referring to GraphiQL: https://github.com/graphql/graphiql

Perhaps you could change it to be a link to that repo?

**Comment by jen729w** [comment]
Ah! Apologies, I’m new to GraphQL. Will do. Thanks.

**Comment by stubailo** [comment]
Woo, thanks!

**Pull request merged**
