### PR TITLE
add hasura.io/learn/ graphql tutorials

### PR DESCRIPTION
**Pull request by praveenweb**
This PR adds a community resource - [GraphQL Tutorials](https://hasura.io/learn/) which is a series of 2 hour tutorials covering various libraries and frameworks (React, Vue, Angular, Elm, ReasonML, React Native, iOS, Android, Flutter)

### CODE REVIEW

**Comment by carolstran** [comment]
👋🏼 Thanks for taking the time to open this pull request! We're currently re-evaluating the structure of this Community page and pausing any changes until after those decisions are made. So I'm going to mark this PR as `On hold` and if you have any thoughts on this topic, it'd be great if you could voice them in #912

**Comment by carolstran** [comment]
Hey hey 👋🏼  the Gatsby migration (#938) has been merged so now we can update the content again. Could you please resolve the conflicts on your branch?

**Comment by praveenweb** [comment]
@carolstran - Hey 👋 I have updated the PR with the latest gatsby changes and in the process the hyperlink as well (since it has changed now).

**Comment by hwillson** [comment]
👋 @praveenweb - sorry for the long delay here! Just a heads up that the site structure has changed a bit more since this PR was updated, such that there is now a `Training courses` section in `src/content/community/Community-Users.md`:

CleanShot 2022-11-11 at 20 18 44

Hasura's content might be a better fit in that section. Would you be up for updating this PR? One thing to mention is that you might be asked to update your description to call out that these are vendor provided training courses (Apollo made similar changes), but I'll definitely defer that decision to others to make sure things remain impartial. 😅 Thanks!

**Comment by jorydotcom** [comment]
@praveenweb 👋🏻 would you be up for updating this PR to add your resource to `src/content/community/Community-Users.md`?

**Comment by praveenweb** [comment]
Closing this in favour of https://github.com/graphql/graphql.github.io/pull/1482

**Pull request closed without merging**
