### PR TITLE
Add mercurius to the proposed Node implementations

### PR DESCRIPTION
**Pull request by nuragic**
Add a link to the mercurius repo (GraphQL server for Fastify).

### CODE REVIEW

**Review by orta — APPROVED** [review]
As this was the first time I'd heard of it, and the downloads are still pretty small in the npm ecosystem, I don't think we should be calling it out as an explicit recommendation outside of the neautral code section: https://graphql.org/code/#javascript

**Review by orta — CHANGES_REQUESTED** [review]
Wrong button

**Comment by orta** [comment]
I've merged https://github.com/graphql/graphql.github.io/pull/1162 which added it to the code page, so I'm going to close this PR - thanks for trying to help improve the docs

**Comment by nuragic** [comment]
Hi @orta, thanks! Fair enough 😄

**Pull request closed without merging**
