### PR TITLE
Add ediket logo to GraphQL users

### PR DESCRIPTION
**Pull request by jeongsd**
https://ediket.com/

### CODE REVIEW

**Comment by wincent** [comment]
@jeongsd: Thanks for this. Before we merge it we'll need the CLA signed as per the bot's comment above.

**Comment by lustdante** [comment]
Hello, my name is Jungwoo Lee and I'm CTO of Ediket, the online freelance marketplace for proofreading service, powered by GraphQL and Relay.

jeongsd is our lead developer who suggested the idea of having ourselves featured as one of active GraphQL users. I have signed CLA for both my personal account and company's. Let me know if you need anything else.

Thank you for replacing REST.

JW

**Comment by wincent** [comment]
Thanks @lustdante. Because of the way the bot works, it expects the submitter of the PR to have signed the CLA. Because you've done the company CLA, can you please send a message to cla@fb.com with a reference to this PR? At the moment, the bot hasn't marked this PR with the cla-signed label because the link between @jeongsd and the company hasn't been established. Thanks!

**Comment by wincent** [comment]
Thanks.

**Pull request merged**
