### PR TITLE
Add Magento logo to users page

### PR DESCRIPTION
**Pull request by jeff-matthews**
Magento is proud to be using GraphQL!

### CODE REVIEW

**Comment by caniszczyk** [comment]
We will be moving to a new landscape+page to track GraphQL users:
https://landscape.graphql.org/category=graph-ql-adopter&format=card-mode&grouping=category

Can you please add your entry here via pull request:
https://github.com/graphql/graphql-landscape#new-entries

You can see this example with Stackshare as an example:
graphql/graphql-landscape#48

**Comment by jeff-matthews** [comment]
Someone already added Magento to the new landscape.

**Comment by caniszczyk** [comment]
Sorry @jeff-matthews that was me lol, forgot, found an easy SVG logo :)

**Comment by jeff-matthews** [comment]
Haha! No problem @caniszczyk. Thanks!

**Pull request closed without merging**
