### PR TITLE
Fixed Typo (I assume the example was changed)

### PR DESCRIPTION
**Pull request by ISNIT0**

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by ISNIT0** [comment]
I'm not about to humor the Facebook Bot. Someone else will need to re-make this PR I guess

**Comment by stubailo** [comment]
The CLA is just to validate that you own the content you are submitting as a PR. It's not super relevant to this particular situation, but I don't see why it would be a bad thing to sign a CLA, in general (a lot of open source projects have or need this)

**Comment by ISNIT0** [comment]
@stubailo I fully appreciate that it may not be an issue for most people, but in this case I'm not prepared to oblige.
Hopefully the typo will be fixed without my details being passed on to Facebook.

**Comment by stubailo** [comment]
Alright, thanks.

**Pull request closed without merging**
