### PR TITLE
Create Frequently Asked Questions (FAQ) Page 

### PR DESCRIPTION
**Pull request by carolstran**
💓  **This PR is part of [Google Season of Docs](https://foundation.graphql.org/news/2020/09/21/google-season-of-docs-2020-participant-carolyn-stransky/)** 💓 

Initial technical implementation of the FAQ page, as well as the first 10 questions that were reviewed and approved in #943. We will continue to update the design, SEO, content, etc. in future PRs.
_Note: Original iteration was done on #929 but updated due to the Gatsby migration._

_Current status:_
* FAQ link added to the header nav
* Questions and answers fully visible on the page (with questions listed at the top)

_Current design:_
Initial implementation of the FAQ page

### CODE REVIEW

**Review by IvanGoncharov — APPROVED** [review]
Looks good 👍 
Disclaimer: I have almost zero knowledge of frontend 😞

**Comment by carolstran** [comment]
No problem @IvanGoncharov! This PR only adds a new Gatsby page based on the existing page structures in this repo, nothing fancy 😊

**Comment by carolstran** [comment]
@orta tagging you as I'm not sure what the process is for deploying a new page, so any insights are appreciated 😇

**Comment by carolstran** [comment]
LOL nevermind @orta, just realized it deploys automatically!

**Pull request merged**
