### PR TITLE
docs: add Pylon service

### PR DESCRIPTION
**Pull request by schettn**
I am the creator of Pylon a code-first approach to GraphQL server development.

In Pylon the GraphQL schema is generated in real-time from your TypeScript definitions, allowing you to focus solely on writing your service logic. This approach significantly improves development speed, enhances type safety, and reduces errors.

GH: https://github.com/getcronit/pylon

### CODE REVIEW

**Comment by schettn** [comment]
image


Should Pylon be moved to "Server" instead of "Services"?

**Comment by Urigo** [comment]
awesome new library!
for my personal learning, can you share how does it differ from other Typescript code first libraries like [Pothos](https://pothos-graphql.dev/) and [Grats](https://github.com/captbaritone/grats)?

**Comment by schettn** [comment]
> awesome new library! for my personal learning, can you share how does it differ from other Typescript code first libraries like [Pothos](https://pothos-graphql.dev/) and [Grats](https://github.com/captbaritone/grats)?

Hi @Urigo!

Thanks a lot! I just relaunched the [Documentation](https://pylon.cronit.io) yesterday and also included the difference between [Pothos](https://pothos-graphql.dev/) and [Grats](https://github.com/captbaritone/grats) in our [FAQ](https://pylon.cronit.io/docs/faq).

**Comment by Urigo** [comment]
Super cool!!
Can you fix prettier and I'll merge?

**Comment by schettn** [comment]
Done.
https://github.com/graphql/graphql.github.io/actions/runs/10307584296

**Comment by Urigo** [comment]
thank you!

**Comment by schettn** [comment]
Hi @Urigo.

I have a quick follow up question:

Why are there no stars/latest releases/licence for Pylon? I thought that I followed an example that includes the stats:

IMG_0102
IMG_0101

**Comment by dimaMachina** [comment]
@schettn fixed!
image

**Pull request merged**
