### PR TITLE
Adding GraphCMS logo

### PR DESCRIPTION
**Pull request by mlukaszczyk**
Added a logo for our new GraphQL based product: GraphCMS - a GraphQL based Headless Content Management

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by mlukaszczyk** [comment]
Please add this changes to your site (:

Thanks a lot!

Michael

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by stubailo** [comment]
Thanks for adding it!

**Pull request merged**
