### PR TITLE
Add documentation for django-graphbox library to GraphQL Python Tools page

### PR DESCRIPTION
**Pull request by yefeza**
Description:

This pull request adds documentation for the django-graphbox library to the GraphQL Python Tools page. The django-graphbox library is a powerful tool for building GraphQL APIs in Python, and this documentation will help users understand its capabilities and use it more effectively.

The documentation includes an overview of the library, installation instructions, and a detailed guide on how to use it with Django to create GraphQL APIs. It also includes code snippets and examples to help users get started quickly.

By adding this documentation, we aim to make it easier for developers to use the django-graphbox library to build high-quality GraphQL APIs in Python. We believe that this will not only benefit the existing users of the library but also attract new users to try it out and contribute to its development.

Overall, we are confident that this documentation will improve the accessibility and usability of the django-graphbox library, and we hope that it will be well-received by the community.

### CODE REVIEW

**Comment by Urigo** [comment]
thank you @yefeza , can you please sign the CLA?

**Comment by yefeza** [comment]
> thank you @yefeza , can you please sign the CLA?

I signed the CLA, but the status don't change. Can you help me with that?
image

**Comment by Urigo** [comment]
@jorydotcom can you see how we can help?

**Comment by yefeza** [comment]
> @jorydotcom can you see how we can help?

I think the problem was caused by commit 6f06a8dac73b71006005b55eca73786e2858981d in which I had forgotten to correctly configure the email. What I will do is close this Pull Request and create another one correcting that issue. Thanks.

**Comment by jorydotcom** [comment]
@yefeza Indeed that is likely the case - make sure any of the email addresses you might use in development are associated with your GitHub account as well as your LF ID (see openprofile.dev to manage your LF ID).

**Pull request closed without merging**
