### PR TITLE
docs: Updating Discord popular channels

### PR DESCRIPTION
**Pull request by Urigo**
@benjie @brianwarner a first try at this, not sure if it's the best but let's have the discussion over this PR

### CODE REVIEW

**Comment by benjie** [comment]
I think Graphile should probably be moved under the Vendors section; I’m happy wit the other changes though.

**Comment by Urigo** [comment]
@benjie do you think The Guild one should also be moved?
it suppose to be general GraphQL but it's ran by us and I guess we are a vendor?

**Comment by Urigo** [comment]
ok I've moved Graphile to vendors.
I've left The Guild in general Discord because that's the actual purpose of the server, not things that are specific for The Guild (and also if one day we'll have an official GraphQL Discord we'll just move everything there).

I've placed Graphile above Prisma because Prisma is no longer GraphQL focused so I think it makes more sense for the user.

@brianwarner @benjie let me know if everything looks ok and I can merge.

**Review by benjie — APPROVED** [review]

**Comment by brianwarner** [comment]
Looks good to me, and I'm glad to see we are continuing to refine these pages after taking them live. Thanks @Urigo!

**Pull request merged**
