### PR TITLE
Add samsarahq/thunder to go implementations list

### PR DESCRIPTION
**Pull request by stephen**

### CODE REVIEW

**Comment by stubailo** [comment]
Thanks @stephen!

**Comment by IvanGoncharov** [comment]
@stubailo It looks like this merge broke [graphql.org](https://graphql.org) see #516 
Not sure what is the root cause.

**Comment by stubailo** [comment]
That's very odd, based on that issue I don't think it's related to the PR to be honest.

**Comment by stubailo** [comment]
Sorry I didn't see the comment about the CNAME - I went to sleep right after merging this!

**Pull request merged**
