### PR TITLE
Add Morpheus GraphQL to the list of GraphQL libraries

### PR DESCRIPTION
**Pull request by nalchevanidze**
[Morpheus GraphQL](https://github.com/morpheusgraphql/morpheus-graphql) is a Haskell GraphQL implementation.  it is maintained and covers almost all functions (except custom directives).

### CODE REVIEW

**Comment by carolstran** [comment]
👋🏼 Thanks for taking the time to open this pull request! We're currently re-evaluating how we handle contributions to this Code page and pausing any changes until after those decisions are made. So I'm going to mark this PR as `On hold` and if you have any thoughts on this topic, it'd be great if you could voice them in #911

**Comment by carolstran** [comment]
Hey hey 👋🏼  the Gatsby migration (#938) has been merged so now we can update the content again. Could you please resolve the conflicts on your branch?

**Comment by nalchevanidze** [comment]
Hi @carolstran. merge conflicht is dissolved.

**Review by carolstran — APPROVED** [review]
I can't properly evaluate the Haskell code, but the rest looks good! It'll be nice to have a Haskell section as well 🤸🏼

**Pull request merged**
