### PR TITLE
Add tags to blog posts & create tag pages

### LINKED ISSUE #1033: Help wanted: add support for categories to the blog
I'm opening this issue as a placeholder, in case someone has some spare cycles and is looking for a way they can help out with the website.

I recently pushed a bunch of new content during the migration from https://foundation.graphql.org to https://graphql.org/foundation. This included quite a few news items, which ended up in a flat list on https://graphql.org/blog/

I added tags to the front matter of each post, and I also found [instructions on adding tags to blog posts](https://www.gatsbyjs.com/docs/adding-tags-and-categories-to-blog-posts/). However, our installation has been customized and the instructions don't quite align with our site. This was my first go with Gatsby, and I wasn't able to get it working. I'm hoping that someone who is a little more familiar with Gatsby and React might do better at implementing nice-looking tag pages than I did.

So, I'm opening this as a "help requested" issue. If you're interested in giving it a shot, please feel free to jump in!

### PR DESCRIPTION
**Pull request by mikeesto**
Closes https://github.com/graphql/graphql.github.io/issues/1033

## Description

This PR adds tags to each blog post. When a tag is clicked on, it navigates to a new `/tags` route that shows all posts with the same tag.

Screen Shot 2021-04-13 at 3 50 07 pm

Apologies for the noise in the diffs. It appears prettier hadn't been run in a while on these files.

### CODE REVIEW

**Review by orta — APPROVED** [review]
Looks good to me

**Comment by brianwarner** [comment]
@mikeesto this is *great*! Thanks for doing this.

Do you know if it's possible to add the tags to the sidebar?

**Comment by mikeesto** [comment]
@brianwarner No worries!

Sure can. Did you have something/a design in mind? This is what I've got running locally:

Screen Shot 2021-04-14 at 6 00 44 pm

**Comment by brianwarner** [comment]
That's great! Can we maybe call it "Categories"?

 I really appreciate you doing this. I also see I didn't use consistent tags when I updated all the posts ("Announcement" vs. "Announcements") :-) I have a few things to push anyhow, I'll fix that when I do.

Thanks again!

**Comment by mikeesto** [comment]
I've changed the section title to 'Categories' and looks good now with the fixed tags :)

**Comment by brianwarner** [comment]
This is really great, @mikeesto. Thanks so much for doing this! One of the nicest parts is that we can now link directly to specific types of content (e.g., press releases, or technical content, or spec announcements, or whatever). LGTM.

**Comment by brianwarner** [comment]
@mikeesto I think I fixed the deploy previews. I'm going to try closing and re-opening this PR to see if that triggers a preview build.

**Review by saihaj — APPROVED** [review]
Looks good! I think we should add linting to CI for prettier checks and add [`gatsby-plugin-typegen` ](https://www.gatsbyjs.com/plugins/gatsby-plugin-typegen/) to generate TypeScript types from queries.

**Comment by brianwarner** [comment]
This one has been open for a bit, so I'm going to go ahead and land it and we can iterate as needed. Thanks again, @mikeesto!

**Pull request merged**
