### PR TITLE
code/lang/js/tools: Add Brangr

### PR DESCRIPTION
**Pull request by networkimprov**
## Description

Add description of the new Brangr open source tool to Code section! Notes:
- __Updated:__ I've fixed the table (previously formatted in Github-flavored markdown) to use HTML.
- __Updated:__ I've added bullets to blurb paragraphs, as the rendered markdown lacks margins between paragraphs.

Preview site - search for `Brangr` on this page:
https://graphqlgithubiosource81460-networkimprovgraphqlgithubiopa.gatsbyjs.io/code/#javascript

### CODE REVIEW

**Comment by ghost** [comment]
## :white_check_mark: graphql.github.io-source deploy preview ready
* [Deploy preview](https://graphqlgithubiosource81460-networkimprovgraphqlgithubiopa.gatsbyjs.io)
* [Build logs](https://gatsbyjs.com/dashboard/9d1fde57-f3aa-4329-a82c-012c8edfaedc/sites/329af4a1-3c84-480d-aebf-182713c94f9b/builds/ead007e8-cc5e-4db6-94d9-e1434ecaf404/details) · **1m** build time
* Performance **49** :orange_circle: · Best Practices **92** :green_heart: · SEO **75** :orange_circle: — [View full report](https://build-ead007e8-cc5e-4db6-94d9-e1434ecaf404.gtsb.io/reports/lighthouse/index.html)

**Comment by networkimprov** [comment]
I've fixed the two issues mentioned in the PR description above.
cc @Urigo

**Comment by Urigo** [comment]
@networkimprov can you fix prettier?

**Comment by networkimprov** [comment]
Uri, done - thanks!

FYI the Prettier check didn't run against the first 4 commits on this branch, the latest of which was a week ago.

Btw, an 80-column limit for markdown text seems needlessly narrow, given that most markdown is natural language.

**Comment by Urigo** [comment]
yes when outside contributors send a PR, I need to manually approve some CI runs, thanks for the patience and sorry for the delay!

**Comment by networkimprov** [comment]
Thanks for approving this!

Any suggestions for mailing lists or discussion forums where I could mention a new GQL open source project?
So far I've only found the graphql.org Discord server...

**Comment by Urigo** [comment]
we are trying to keep all community links up to date here: https://graphql.org/community/
if you think there are missing places there, let us know and we'll add these there

**Pull request merged**
