### PR TITLE
Add gqlclient to Go libs

### PR DESCRIPTION
**Pull request by emersion**

### CODE REVIEW

**Comment by orta** [comment]
^ CLA needs signing I'm afraid

**Comment by emersion** [comment]
https://drewdevault.com/2018/10/05/Dont-sign-a-CLA.html

**Comment by orta** [comment]
Then I can't merge it, sorry, I'd recommend asking someone else to send the PR 👍🏻

**Comment by emersion** [comment]
No, I won't ask someone else to give up their right for your project.

**Pull request closed without merging**
