### PR TITLE
Add mongo-graphql-schema to the Code page

### PR DESCRIPTION
**Pull request by arackaf**
Hi.  This PR adds my mongo-graphql-schema to the Code page.  Hopefully it's a good fit :)

### CODE REVIEW

**Comment by arackaf** [comment]
Hi - the CLA has been signed - I don't see any update comments, but it should be signed now.  Let me know if it's somehow not and I'd be happy to do whatever else I need :)

**Comment by stubailo** [comment]
@arackaf thanks for the PR, but this doesn't seem like a good fit for this list, which is more low-level implementations rather than starter kits or higher level libraries. I think this library would fit better on https://github.com/chentsulin/awesome-graphql

**Comment by arackaf** [comment]
@stubailo thanks - but are you sure?  Mine seems like the Mongo equivalent of this (which is also listed on the same page)

https://github.com/graphql-dotnet/graphql-dotnet 

if not no biggie :)

**Comment by stubailo** [comment]
I haven't looked in detail, but I suspect that project is the core implementation of GraphQL for C#, which isn't specific to a particular database, and doesn't use a separate implementation. .NET is more like Node.js than it is like MongoDB.

**Pull request closed without merging**
