### PR TITLE
link to getting started with FaunaDB's GraphQL API

### PR DESCRIPTION
**Pull request by jchris**
FaunaDB offers a free, one-click GraphQL backend, ideal for quickly starting new project.

### CODE REVIEW

**Comment by carolstran** [comment]
👋🏼 Thanks for taking the time to open this pull request! We're currently re-evaluating the structure of this Community page and pausing any changes until after those decisions are made. So I'm going to mark this PR as `On hold` and if you have any thoughts on this topic, it'd be great if you could voice them in #912

**Comment by carolstran** [comment]
Hey hey 👋🏼  the Gatsby migration (#938) has been merged so now we can update the content again. Could you please resolve the conflicts on your branch?

**Comment by Urigo** [comment]
@jchris What do you think about adding a link to the FounaDB blog instead of individual posts?
Maybe even link to the blog with the GraphQL filter like this? 
https://fauna.com/blog?category=graphql

If so, maybe we can redo this once this would be merged: https://github.com/graphql/graphql.github.io/pull/1288

**Comment by Urigo** [comment]
closing for now, if you think there is still think this is needed after the new blogs section change, please submit again

**Pull request closed without merging**
