### PR TITLE
Change charter links to evergreen URLs

### PR DESCRIPTION
**Pull request by brianwarner**
Remove the static PDF previews of the LF and GraphQL Foundation membership applications, and link to evergreen URLs instead.

Signed-off-by: Brian Warner <brian@bdwarner.com>

Closes #<issue number>

### CODE REVIEW

**Comment by brianwarner** [comment]
Builds fine locally, but the build is failing at Netlify. I'll attempt to rerun the jobs later.

**Comment by Urigo** [comment]
@jorydotcom is this still needed?

**Comment by jorydotcom** [comment]
Actually yeah, this would be the preferable way to do it @Urigo - if/when we ever make updates to the Agreements, this would update the file at the source, so we don't have to remember to make the change I made in that other PR. May be better to close this PR and open a fresh one though, given the age/conflicts

**Comment by Urigo** [comment]
@jorydotcom are you able to open a new one or you prefer that I do it?

**Comment by enisdenjo** [comment]
@jorydotcom @brianwarner am closing this due to staleness. Please open a new PR when ready. Thanks!

**Pull request closed without merging**
