### PR TITLE
Updated GraphQL API for WordPress website URL

### PR DESCRIPTION
**Pull request by leoloso**
## Description

Update server's website to its new site https://graphql-api.com

### CODE REVIEW

**Comment by orta** [comment]
👍🏻 cool, looks good to me

**Comment by leoloso** [comment]
Thanks for merging @orta. Any chance to also merge #981? Because the description for the GraphQL API for WordPress reads "Based on GraphQL by PoP", which is why I didn't add implementation details here, since they were already added to this other server

**Comment by orta** [comment]
Great point, I missed that!

**Comment by leoloso** [comment]
Lovely, thanks!

GraphQL by PoP is still not in the list though, and it's been over 1 hour since merged. Does it take long to deploy the site? Or if not, maybe there's some issue going on?

https://graphql.org/code/#php

If there's an issue, it may be because both GraphQL by PoP and GraphQL API for WordPress have leoloso/PoP as repo... (it's the monorepo containing both projects)

**Comment by leoloso** [comment]
It's there now, great!

**Pull request merged**
