### PR TITLE
Adding Scaphold

### PR DESCRIPTION
**Pull request by vning93**
Scaphold.io: GraphQL Backend as a Service

### CODE REVIEW

**Comment by stubailo** [comment]
@vning93 can you separately PR for the logo in the users page and the community resources page, please?

**Comment by vning93** [comment]
@stubailo I actually tried doing that to begin with but git automatically squashed my commits into the same PR. Is that alright?

**Comment by vning93** [comment]
Just updated given your feedback. Thanks for putting us on the site!

**Comment by asiandrummer** [comment]
@vning93 - sorry to take so long to respond.
> I actually tried doing that to begin with but git automatically squashed my commits into the same PR. Is that alright?

Not trying to be granular, but I also think it'd be better to have two different PRs that touch different parts of the pages. I'd appreciate if you could submit another PR for the community resources page please :D

I think we're ready to merge the logo, but I'm seeing a merge conflict. Could you also resolve that?

**Pull request closed without merging**
