### PR TITLE
Reference to Issue #955- Made the Navbar Responsive by adding Toggle button option

### LINKED ISSUE #955: Menu overflowing on mobile viewports
Screen Shot 2020-11-07 at 12 10 46 pm

It might be worth looking at using a hamburger menu (or similar) for mobile.

### PR DESCRIPTION
**Pull request by rt1301**
Fix: #955 - I have made the navbar responsive by adding toggle button functionality for smaller screen size. I have also updated the search input style sheet, so that it is visible at all screen sizes.

**Screen Shots of the Fix**
ss4
ss3
ss2
ss1

Tagging @carolstran & @mikeesto  for review. Thanks!

### CODE REVIEW

**Review by mikeesto — CHANGES_REQUESTED** [review]
Thanks for taking the time to work on this @rt1301. 

Could you please fix up the hover color on nav items, it seems to have inadvertently changed from white to black:

Screen Shot 2020-11-21 at 12 52 37 pm

**Comment by rt1301** [comment]
@mikeesto Ok I'll look into it

**Comment by rt1301** [comment]
@mikeesto @carolstran I fixed the hover color bug on the navbar links, please take a look. Thanks!
Screenshot from 2020-11-22 20-41-06

**Comment by rt1301** [comment]
@carolstran @mikeesto  are any other changes required for the responsive navbar?

**Comment by Urigo** [comment]
@rt1301 does this fix still needed on the new website?

**Comment by rt1301** [comment]
@Urigo this is actually now fixed in the new website and I don't think is required any more. Thanks!

**Comment by Urigo** [comment]
thanks @rt1301 !

**Pull request closed without merging**
