### PR TITLE
feat: add wundergraph to gateway section

### PR DESCRIPTION
**Pull request by jensneuse**
## Description

As discussed with Uri, this adds WunderGraph to the newly created Gateway section.

### CODE REVIEW

**Comment by hwillson** [comment]
👋 @jensneuse - thanks for this!

Hmmm - I wonder if creating a new "Gateways" section on this page is getting a bit too specific, and breaks the more high-level type of bucketing in place on the page. Gateways are a pretty specific subset of "Tools", and there aren't (currently) a lot of GraphQL gateways out there, so I'm not sure if calling them out separately will add much value to folks visiting the page. Don't get me wrong, I will happily submit a PR to add Apollo Router if we want to create this new category 😂, but I think this extra category might be splitting things up a bit too much. That being said, I'd love to hear what others in @graphql/content think.

**Comment by Urigo** [comment]
Great ideas @jensneuse and @hwillson !

Adding a bit more context on the last overall we've mode for the code section, we had thought initially to create a couple of sub-categories under tools, but at the time there weren't enough, so we thought to leave it as general "tools" section and see when new things will up to differentiate.

I think Gateways/Supergraphs looks like an important category and the fact that Apollo Router, Schema Stitching and other very popular and important tools are not represented here points to the fact we might want to add that section.

I guess the open question for me would be if we want to add it to the top category (next to `tools`) or a subcategory of `tools`.
Tools currently is focused on things that are language agnostic, which I believe Gateways and Supergraphs are, so if we follow that direction, it means as a subcategory under tools.

Also I can think of a couple of new subcategories of language agnostic tools, so I guess my vote is to put it as a first subsection under `Tools` and place all existing links under `general` subsection.

Also, personally I would name this category `Gateways and Supergraphs` as any GraphQL library could act as a gateway and I think the distinguishing factor here is a tool that orchestrates underlying, remote GraphQL servers, so the rename would make it more clear.

I will follow up on this PR with other tools that fit that subcategory and at least one more sub category.

@jensneuse @hwillson does that fit your directions?

**Comment by jensneuse** [comment]
> Great ideas @jensneuse and @hwillson !
> 
> Adding a bit more context on the last overall we've mode for the code section, we had thought initially to create a couple of sub-categories under tools, but at the time there weren't enough, so we thought to leave it as general "tools" section and see when new things will up to differentiate.
> 
> I think Gateways/Supergraphs looks like an important category and the fact that Apollo Router, Schema Stitching and other very popular and important tools are not represented here points to the fact we might want to add that section.
> 
> I guess the open question for me would be if we want to add it to the top category (next to `tools`) or a subcategory of `tools`.
> Tools currently is focused on things that are language agnostic, which I believe Gateways and Supergraphs are, so if we follow that direction, it means as a subcategory under tools.
> 
> Also I can think of a couple of new subcategories of language agnostic tools, so I guess my vote is to put it as a first subsection under `Tools` and place all existing links under `general` subsection.
> 
> Also, personally I would name this category `Gateways and Supergraphs` as any GraphQL library could act as a gateway and I think the distinguishing factor here is a tool that orchestrates underlying, remote GraphQL servers, so the rename would make it more clear.
> 
> I will follow up on this PR with other tools that fit that subcategory and at least one more sub category.
> 
> @jensneuse @hwillson does that fit your directions?

That's in line with my thinking. What should we do with this PR? Should I make changes as you proposed? Do you want to take over and arrange the content properly? I have to admit I don't feel 100% comfortable with the codebase and don't want to introduce a new style or patterns when introducing this new category.

**Comment by Urigo** [comment]
sure, if you are not comfortable I can send a new PR instead.
Let's wait for @hwillson's opinion first

**Comment by hwillson** [comment]
Thanks for the additional background @Urigo - this all sounds great to me!

**Comment by jensneuse** [comment]
> sure, if you are not comfortable I can send a new PR instead. Let's wait for @hwillson's opinion first

Ok, then I'd welcome if you can take over incorporating this PR into the new structure. Thanks.

**Comment by Urigo** [comment]
done in https://github.com/graphql/graphql.github.io/pull/1330

**Pull request closed without merging**
