### PR TITLE
Add Caliban to the list of GraphQL libraries

### PR DESCRIPTION
**Pull request by ghostdogpr**
Add [Caliban](https://ghostdogpr.github.io/caliban/), a Scala library for creating both GraphQL servers and clients.

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Solved the conflicts. Any chance to get this one merged? 😄

**Comment by carolstran** [comment]
👋🏼 Thanks for taking the time to open this pull request! We're currently re-evaluating how we handle contributions to this Code page and pausing any changes until after those decisions are made. So I'm going to mark this PR as `On hold` and if you have any thoughts on this topic, it'd be great if you could voice them in #911

**Comment by bengraygh** [comment]
Caliban is a serious functional implementation of the GraphQL specification for the scala language, which is actively developed and has widespread and increasing adoption. It has been promoted as a GraphQL library by the founder of zio (https://twitter.com/jdegoes/status/1219690876047413248?lang=en). Is there anyone who feels that this library should not be included for some reason?

**Comment by carolstran** [comment]
Hey hey 👋🏼  the Gatsby migration (#938) has been merged so now we can update the content again. Could you please resolve the conflicts on your branch?

**Comment by ghostdogpr** [comment]
Closing in favor of #927 that has an example.

**Pull request closed without merging**
