### PR TITLE
Add Hudl to the list of companies that use GraphQL

### PR DESCRIPTION
**Pull request by mihai**
We are very excited about GraphQL and we've been using it at [Hudl](https://www.hudl.com) for about half a year in production.

Let me know if this addition should be done differently.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by leebyron** [comment]
That's awesome you're using GraphQL in production!

Unfortunately we'd like to reserve the logos that appear on index.html for companies that have broad name recognition like Github & Intuit.

I'd love to still keep track of logos from companies using GraphQL though, so give me a moment to create a more dedicated and appropriate space for this addition.

**Comment by mihai** [comment]
> I'd love to still keep track of logos from companies using GraphQL though, so give me a moment to create a more dedicated and appropriate space for this addition.

Sounds good @leebyron! Let me know when you have that and I can update this PR.

**Comment by leebyron** [comment]
Done! Thanks for the inspiration.

#89 added this, which is deploying now and you can find on http://graphql.org/users/

Hopefully it's an easy update.

**Comment by mihai** [comment]
@leebyron updated! Thanks for getting the users page setup so quickly 👍

**Comment by leebyron** [comment]
Could you remove the margins from the image file? They're going to make your logo look super tiny!

**Comment by mihai** [comment]
> Could you remove the margins from the image file?

Good point, removed them now 👍

**Comment by leebyron** [comment]
sweet

**Pull request merged**
