### PR TITLE
added UST Global company logo and link in users page

### PR DESCRIPTION
**Pull request by rakeshpaul-ustglobal**

### CODE REVIEW

**Comment by stubailo** [comment]
Do you mind signing the CLA and rebasing?

**Comment by rakeshpaul-ustglobal** [comment]
@stubailo CLA is signed but not sure why it is not showing.. After doing the merge only I realized, I should be doing a rebase instead.. Let me know if I need to do something else from my end to get this merged..

Kind Regards

**Comment by stubailo** [comment]
Looks great, thanks!

**Comment by rakeshpaul-ustglobal** [comment]
@stubailo thank you so much, warm regards

**Pull request merged**
