### PR TITLE
Fixed Broken links on Introspection route

### PR DESCRIPTION
**Pull request by shan7030**
## Description

1. Fixed the link to starWarsIntrospection-test.ts in Introspection section which is recently migrated to .ts from .js
2. Fixed the link to introspection file in GraphQL.js which is recently migrated to .ts from .js

### CODE REVIEW

**Comment by saihaj** [comment]
Hey @shan7030 thanks for the changes. There are possibly many broken links because of TS migration. These docs are outdated and something we plan to work and improve on as part of v16 release plan https://github.com/graphql/graphql-js/issues/2860 . Idea is to generate API docs using TS doc so we have latest docs

**Comment by shan7030** [comment]
Hi @saihaj , thanks for updating me about this. So, do I close this PR or would it be good idea to merge this for the time being?

**Comment by saihaj** [comment]
I guess we can merge this in for time being. I will be making a meta issue to track all the documentation related issues so that everything can be addressed.

**Comment by saihaj** [comment]
Resolved in #1056 @brianwarner we can close this

**Comment by brianwarner** [comment]
Thank you! I've just merged the other PR.

**Pull request closed without merging**
