### PR TITLE
New Reddit communities to add to Resources

### PR DESCRIPTION
**Pull request by jmpreston**
## Reddit Communities:
- [r/graphql] (https://www.reddit.com/r/graphql)
- [r/Nestjs_framework including GraphQL / Apollo Angular style] (https://www.reddit.com/r/Nestjs_framework/)

### CODE REVIEW

**Comment by carolstran** [comment]
👋🏼 Thanks for taking the time to open this pull request! We're currently re-evaluating the structure of this Community page and pausing any changes until after those decisions are made. So I'm going to mark this PR as `On hold` and if you have any thoughts on this topic, it'd be great if you could voice them in #912

**Comment by carolstran** [comment]
Hey hey 👋🏼  the Gatsby migration (#938) has been merged so now we can update the content again. Could you please resolve the conflicts on your branch?

**Comment by hwillson** [comment]
Thanks for this @jmpreston and sorry for the delay. The community resources section of the site has gone through a few iterations since this PR was opened, and is now more focused on general how to learn/use GraphQL content. NestJS is awesome, but linking to the NestJS subreddit as the only Reddit entry on the page seems a bit out of place with the overall theme of the page. We'll close this for now, but thanks again for the suggestion.

**Comment by Urigo** [comment]
Agree with @hwillson that NestJS is a bit too specific, but adding the main GraphQL Reddit community is beneficial!
Sent a PR here: https://github.com/graphql/graphql.github.io/pull/1289

**Pull request closed without merging**
