### PR TITLE
Added "GraphQL API for WordPress" on the PHP list

### PR DESCRIPTION
**Pull request by leoloso**

### CODE REVIEW

**Comment by carolstran** [comment]
👋🏼 Thanks for taking the time to open this pull request! We're currently re-evaluating how we handle contributions to this Code page and pausing any changes until after those decisions are made. So I'm going to mark this PR as `On hold` and if you have any thoughts on this topic, it'd be great if you could voice them in #911

**Comment by leoloso** [comment]
Alright, thanks for the info.

**Comment by carolstran** [comment]
Hey hey 👋🏼  the Gatsby migration (#938) has been merged so now we can update the content again. Could you please resolve the conflicts on your branch?

**Comment by leoloso** [comment]
Hi @carolstran conflicts resolved now :)

**Comment by carolstran** [comment]
Ack we just merged another PR and now there's a new conflict, but it should be quick to resolve! Once that's done then I can merge 🚀

**Review by carolstran — APPROVED** [review]

**Comment by leoloso** [comment]
@carolstran fixed now :)

**Comment by carolstran** [comment]
You're great, thank you!

**Pull request merged**
