### PR TITLE
List prominent GraphQL service providers on the code page

### PR DESCRIPTION
**Pull request by Sonicrida**
I was attempting to assist with the request mentioned in #283 . This is my first time contributing to an open source project so feel free to let me know if I've done something incorrectly 😄. @stubailo mentioned 5-6 different services but I could only find these 4 just by searching for GraphQL services. I wasn't too sure about how to order them so I figured that I would list Graphcool and Scaphold first since those are more targeted towards general usage while the other two are more specific in their use cases.

### CODE REVIEW

**Comment by stubailo** [comment]
Would also appreciate a mention of http://www.apollodata.com/optics/, a GraphQL-specific performance tool.

Also, Reindex doesn't offer the GraphQL service anymore: http://reindex.io/

**Comment by Sonicrida** [comment]
Good call on Apollo Optics! Also, I believe that Reindex is still offering their service at this url if I'm not mistaken: https://www.reindex.io/baas/ It seems that I am still able to sign up.

**Comment by wincent** [comment]
Thanks a bunch @Sonicrida. Will merge with a few small tweaks applied on top.

**Comment by Sonicrida** [comment]
Thanks @wincent .That's awesome! I'm glad to help!

**Pull request merged**
